// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.23.1
// source: api/common/channel.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChannelSelectionMethod int32

const (
	ChannelSelectionMethod_CHANNEL_SELECTION_METHOD_UNKNOWN ChannelSelectionMethod = 0
	ChannelSelectionMethod_AUTONOMOUS_CHANNEL_SELECTION     ChannelSelectionMethod = 1
	ChannelSelectionMethod_CHANNEL_SELECTION_BY_CONTROLLER  ChannelSelectionMethod = 2
)

// Enum value maps for ChannelSelectionMethod.
var (
	ChannelSelectionMethod_name = map[int32]string{
		0: "CHANNEL_SELECTION_METHOD_UNKNOWN",
		1: "AUTONOMOUS_CHANNEL_SELECTION",
		2: "CHANNEL_SELECTION_BY_CONTROLLER",
	}
	ChannelSelectionMethod_value = map[string]int32{
		"CHANNEL_SELECTION_METHOD_UNKNOWN": 0,
		"AUTONOMOUS_CHANNEL_SELECTION":     1,
		"CHANNEL_SELECTION_BY_CONTROLLER":  2,
	}
)

func (x ChannelSelectionMethod) Enum() *ChannelSelectionMethod {
	p := new(ChannelSelectionMethod)
	*p = x
	return p
}

func (x ChannelSelectionMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChannelSelectionMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_api_common_channel_proto_enumTypes[0].Descriptor()
}

func (ChannelSelectionMethod) Type() protoreflect.EnumType {
	return &file_api_common_channel_proto_enumTypes[0]
}

func (x ChannelSelectionMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *ChannelSelectionMethod) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = ChannelSelectionMethod(num)
	return nil
}

// Deprecated: Use ChannelSelectionMethod.Descriptor instead.
func (ChannelSelectionMethod) EnumDescriptor() ([]byte, []int) {
	return file_api_common_channel_proto_rawDescGZIP(), []int{0}
}

type BandProfile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChannelWidthHz *uint64                `protobuf:"varint,2,opt,name=channel_width_hz,json=channelWidthHz" json:"channel_width_hz,omitempty"`
	RateTable      *AdaptiveDataRateTable `protobuf:"bytes,3,opt,name=rate_table,json=rateTable" json:"rate_table,omitempty"`
}

func (x *BandProfile) Reset() {
	*x = BandProfile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_common_channel_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BandProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BandProfile) ProtoMessage() {}

func (x *BandProfile) ProtoReflect() protoreflect.Message {
	mi := &file_api_common_channel_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BandProfile.ProtoReflect.Descriptor instead.
func (*BandProfile) Descriptor() ([]byte, []int) {
	return file_api_common_channel_proto_rawDescGZIP(), []int{0}
}

func (x *BandProfile) GetChannelWidthHz() uint64 {
	if x != nil && x.ChannelWidthHz != nil {
		return *x.ChannelWidthHz
	}
	return 0
}

func (x *BandProfile) GetRateTable() *AdaptiveDataRateTable {
	if x != nil {
		return x.RateTable
	}
	return nil
}

var File_api_common_channel_proto protoreflect.FileDescriptor

var file_api_common_channel_proto_rawDesc = []byte{
	0x0a, 0x18, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x63, 0x68, 0x61,
	0x6e, 0x6e, 0x65, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1c, 0x61, 0x61, 0x6c, 0x79,
	0x72, 0x69, 0x61, 0x2e, 0x73, 0x70, 0x61, 0x63, 0x65, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x1a, 0x20, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x77, 0x69, 0x72, 0x65, 0x6c, 0x65, 0x73, 0x73, 0x5f, 0x6d, 0x6f,
	0x64, 0x63, 0x6f, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x9b, 0x01, 0x0a, 0x0b, 0x42,
	0x61, 0x6e, 0x64, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x12, 0x28, 0x0a, 0x10, 0x63, 0x68,
	0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x5f, 0x77, 0x69, 0x64, 0x74, 0x68, 0x5f, 0x68, 0x7a, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x0e, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x57, 0x69, 0x64,
	0x74, 0x68, 0x48, 0x7a, 0x12, 0x52, 0x0a, 0x0a, 0x72, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x61, 0x62,
	0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x33, 0x2e, 0x61, 0x61, 0x6c, 0x79, 0x72,
	0x69, 0x61, 0x2e, 0x73, 0x70, 0x61, 0x63, 0x65, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x41, 0x64, 0x61, 0x70, 0x74, 0x69, 0x76, 0x65,
	0x44, 0x61, 0x74, 0x61, 0x52, 0x61, 0x74, 0x65, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x09, 0x72,
	0x61, 0x74, 0x65, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x4a, 0x04, 0x08, 0x01, 0x10, 0x02, 0x4a, 0x08,
	0x08, 0x04, 0x10, 0x80, 0x80, 0x80, 0x80, 0x02, 0x2a, 0x85, 0x01, 0x0a, 0x16, 0x43, 0x68, 0x61,
	0x6e, 0x6e, 0x65, 0x6c, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x74,
	0x68, 0x6f, 0x64, 0x12, 0x24, 0x0a, 0x20, 0x43, 0x48, 0x41, 0x4e, 0x4e, 0x45, 0x4c, 0x5f, 0x53,
	0x45, 0x4c, 0x45, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x4d, 0x45, 0x54, 0x48, 0x4f, 0x44, 0x5f,
	0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x20, 0x0a, 0x1c, 0x41, 0x55, 0x54,
	0x4f, 0x4e, 0x4f, 0x4d, 0x4f, 0x55, 0x53, 0x5f, 0x43, 0x48, 0x41, 0x4e, 0x4e, 0x45, 0x4c, 0x5f,
	0x53, 0x45, 0x4c, 0x45, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0x01, 0x12, 0x23, 0x0a, 0x1f, 0x43,
	0x48, 0x41, 0x4e, 0x4e, 0x45, 0x4c, 0x5f, 0x53, 0x45, 0x4c, 0x45, 0x43, 0x54, 0x49, 0x4f, 0x4e,
	0x5f, 0x42, 0x59, 0x5f, 0x43, 0x4f, 0x4e, 0x54, 0x52, 0x4f, 0x4c, 0x4c, 0x45, 0x52, 0x10, 0x02,
	0x42, 0x44, 0x0a, 0x20, 0x63, 0x6f, 0x6d, 0x2e, 0x61, 0x61, 0x6c, 0x79, 0x72, 0x69, 0x61, 0x2e,
	0x73, 0x70, 0x61, 0x63, 0x65, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x5a, 0x20, 0x61, 0x61, 0x6c, 0x79, 0x72, 0x69, 0x61, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x73, 0x70, 0x61, 0x63, 0x65, 0x74, 0x69, 0x6d, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
}

var (
	file_api_common_channel_proto_rawDescOnce sync.Once
	file_api_common_channel_proto_rawDescData = file_api_common_channel_proto_rawDesc
)

func file_api_common_channel_proto_rawDescGZIP() []byte {
	file_api_common_channel_proto_rawDescOnce.Do(func() {
		file_api_common_channel_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_common_channel_proto_rawDescData)
	})
	return file_api_common_channel_proto_rawDescData
}

var file_api_common_channel_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_common_channel_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_common_channel_proto_goTypes = []interface{}{
	(ChannelSelectionMethod)(0),   // 0: aalyria.spacetime.api.common.ChannelSelectionMethod
	(*BandProfile)(nil),           // 1: aalyria.spacetime.api.common.BandProfile
	(*AdaptiveDataRateTable)(nil), // 2: aalyria.spacetime.api.common.AdaptiveDataRateTable
}
var file_api_common_channel_proto_depIdxs = []int32{
	2, // 0: aalyria.spacetime.api.common.BandProfile.rate_table:type_name -> aalyria.spacetime.api.common.AdaptiveDataRateTable
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_common_channel_proto_init() }
func file_api_common_channel_proto_init() {
	if File_api_common_channel_proto != nil {
		return
	}
	file_api_common_wireless_modcod_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_api_common_channel_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BandProfile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_common_channel_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_common_channel_proto_goTypes,
		DependencyIndexes: file_api_common_channel_proto_depIdxs,
		EnumInfos:         file_api_common_channel_proto_enumTypes,
		MessageInfos:      file_api_common_channel_proto_msgTypes,
	}.Build()
	File_api_common_channel_proto = out.File
	file_api_common_channel_proto_rawDesc = nil
	file_api_common_channel_proto_goTypes = nil
	file_api_common_channel_proto_depIdxs = nil
}
