// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api/cdpi/v1alpha/cdpi.proto

package com.aalyria.spacetime.api.cdpi.v1alpha;

/**
 * Protobuf type {@code aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest}
 */
public final class CdpiRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest)
    CdpiRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CdpiRequest.newBuilder() to construct.
  private CdpiRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CdpiRequest() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CdpiRequest();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.aalyria.spacetime.api.cdpi.v1alpha.CdpiProto.internal_static_aalyria_spacetime_api_cdpi_v1alpha_CdpiRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.aalyria.spacetime.api.cdpi.v1alpha.CdpiProto.internal_static_aalyria_spacetime_api_cdpi_v1alpha_CdpiRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.class, com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Builder.class);
  }

  public interface HelloOrBuilder extends
      // @@protoc_insertion_point(interface_extends:aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Hello)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string node_id = 1 [json_name = "nodeId"];</code>
     * @return Whether the nodeId field is set.
     */
    boolean hasNodeId();
    /**
     * <code>optional string node_id = 1 [json_name = "nodeId"];</code>
     * @return The nodeId.
     */
    java.lang.String getNodeId();
    /**
     * <code>optional string node_id = 1 [json_name = "nodeId"];</code>
     * @return The bytes for nodeId.
     */
    com.google.protobuf.ByteString
        getNodeIdBytes();

    /**
     * <code>optional uint32 channel_priority = 2 [json_name = "channelPriority"];</code>
     * @return Whether the channelPriority field is set.
     */
    boolean hasChannelPriority();
    /**
     * <code>optional uint32 channel_priority = 2 [json_name = "channelPriority"];</code>
     * @return The channelPriority.
     */
    int getChannelPriority();
  }
  /**
   * Protobuf type {@code aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Hello}
   */
  public static final class Hello extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Hello)
      HelloOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Hello.newBuilder() to construct.
    private Hello(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Hello() {
      nodeId_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Hello();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.aalyria.spacetime.api.cdpi.v1alpha.CdpiProto.internal_static_aalyria_spacetime_api_cdpi_v1alpha_CdpiRequest_Hello_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.aalyria.spacetime.api.cdpi.v1alpha.CdpiProto.internal_static_aalyria_spacetime_api_cdpi_v1alpha_CdpiRequest_Hello_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Hello.class, com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Hello.Builder.class);
    }

    private int bitField0_;
    public static final int NODE_ID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object nodeId_ = "";
    /**
     * <code>optional string node_id = 1 [json_name = "nodeId"];</code>
     * @return Whether the nodeId field is set.
     */
    @java.lang.Override
    public boolean hasNodeId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string node_id = 1 [json_name = "nodeId"];</code>
     * @return The nodeId.
     */
    @java.lang.Override
    public java.lang.String getNodeId() {
      java.lang.Object ref = nodeId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          nodeId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string node_id = 1 [json_name = "nodeId"];</code>
     * @return The bytes for nodeId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNodeIdBytes() {
      java.lang.Object ref = nodeId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nodeId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CHANNEL_PRIORITY_FIELD_NUMBER = 2;
    private int channelPriority_ = 0;
    /**
     * <code>optional uint32 channel_priority = 2 [json_name = "channelPriority"];</code>
     * @return Whether the channelPriority field is set.
     */
    @java.lang.Override
    public boolean hasChannelPriority() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional uint32 channel_priority = 2 [json_name = "channelPriority"];</code>
     * @return The channelPriority.
     */
    @java.lang.Override
    public int getChannelPriority() {
      return channelPriority_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, nodeId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeUInt32(2, channelPriority_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, nodeId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, channelPriority_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Hello)) {
        return super.equals(obj);
      }
      com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Hello other = (com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Hello) obj;

      if (hasNodeId() != other.hasNodeId()) return false;
      if (hasNodeId()) {
        if (!getNodeId()
            .equals(other.getNodeId())) return false;
      }
      if (hasChannelPriority() != other.hasChannelPriority()) return false;
      if (hasChannelPriority()) {
        if (getChannelPriority()
            != other.getChannelPriority()) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasNodeId()) {
        hash = (37 * hash) + NODE_ID_FIELD_NUMBER;
        hash = (53 * hash) + getNodeId().hashCode();
      }
      if (hasChannelPriority()) {
        hash = (37 * hash) + CHANNEL_PRIORITY_FIELD_NUMBER;
        hash = (53 * hash) + getChannelPriority();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Hello parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Hello parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Hello parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Hello parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Hello parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Hello parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Hello parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Hello parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Hello parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Hello parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Hello parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Hello parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Hello prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Hello}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Hello)
        com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.HelloOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.aalyria.spacetime.api.cdpi.v1alpha.CdpiProto.internal_static_aalyria_spacetime_api_cdpi_v1alpha_CdpiRequest_Hello_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.aalyria.spacetime.api.cdpi.v1alpha.CdpiProto.internal_static_aalyria_spacetime_api_cdpi_v1alpha_CdpiRequest_Hello_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Hello.class, com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Hello.Builder.class);
      }

      // Construct using com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Hello.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        nodeId_ = "";
        channelPriority_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.aalyria.spacetime.api.cdpi.v1alpha.CdpiProto.internal_static_aalyria_spacetime_api_cdpi_v1alpha_CdpiRequest_Hello_descriptor;
      }

      @java.lang.Override
      public com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Hello getDefaultInstanceForType() {
        return com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Hello.getDefaultInstance();
      }

      @java.lang.Override
      public com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Hello build() {
        com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Hello result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Hello buildPartial() {
        com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Hello result = new com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Hello(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Hello result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.nodeId_ = nodeId_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.channelPriority_ = channelPriority_;
          to_bitField0_ |= 0x00000002;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Hello) {
          return mergeFrom((com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Hello)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Hello other) {
        if (other == com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Hello.getDefaultInstance()) return this;
        if (other.hasNodeId()) {
          nodeId_ = other.nodeId_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.hasChannelPriority()) {
          setChannelPriority(other.getChannelPriority());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                nodeId_ = input.readBytes();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 16: {
                channelPriority_ = input.readUInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object nodeId_ = "";
      /**
       * <code>optional string node_id = 1 [json_name = "nodeId"];</code>
       * @return Whether the nodeId field is set.
       */
      public boolean hasNodeId() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional string node_id = 1 [json_name = "nodeId"];</code>
       * @return The nodeId.
       */
      public java.lang.String getNodeId() {
        java.lang.Object ref = nodeId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            nodeId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string node_id = 1 [json_name = "nodeId"];</code>
       * @return The bytes for nodeId.
       */
      public com.google.protobuf.ByteString
          getNodeIdBytes() {
        java.lang.Object ref = nodeId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nodeId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string node_id = 1 [json_name = "nodeId"];</code>
       * @param value The nodeId to set.
       * @return This builder for chaining.
       */
      public Builder setNodeId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        nodeId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>optional string node_id = 1 [json_name = "nodeId"];</code>
       * @return This builder for chaining.
       */
      public Builder clearNodeId() {
        nodeId_ = getDefaultInstance().getNodeId();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>optional string node_id = 1 [json_name = "nodeId"];</code>
       * @param value The bytes for nodeId to set.
       * @return This builder for chaining.
       */
      public Builder setNodeIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        nodeId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private int channelPriority_ ;
      /**
       * <code>optional uint32 channel_priority = 2 [json_name = "channelPriority"];</code>
       * @return Whether the channelPriority field is set.
       */
      @java.lang.Override
      public boolean hasChannelPriority() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional uint32 channel_priority = 2 [json_name = "channelPriority"];</code>
       * @return The channelPriority.
       */
      @java.lang.Override
      public int getChannelPriority() {
        return channelPriority_;
      }
      /**
       * <code>optional uint32 channel_priority = 2 [json_name = "channelPriority"];</code>
       * @param value The channelPriority to set.
       * @return This builder for chaining.
       */
      public Builder setChannelPriority(int value) {

        channelPriority_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 channel_priority = 2 [json_name = "channelPriority"];</code>
       * @return This builder for chaining.
       */
      public Builder clearChannelPriority() {
        bitField0_ = (bitField0_ & ~0x00000002);
        channelPriority_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Hello)
    }

    // @@protoc_insertion_point(class_scope:aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Hello)
    private static final com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Hello DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Hello();
    }

    public static com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Hello getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Hello>
        PARSER = new com.google.protobuf.AbstractParser<Hello>() {
      @java.lang.Override
      public Hello parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Hello> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Hello> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Hello getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Response)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int64 request_id = 1 [json_name = "requestId"];</code>
     * @return Whether the requestId field is set.
     */
    boolean hasRequestId();
    /**
     * <code>optional int64 request_id = 1 [json_name = "requestId"];</code>
     * @return The requestId.
     */
    long getRequestId();

    /**
     * <code>optional .google.rpc.Status status = 2 [json_name = "status"];</code>
     * @return Whether the status field is set.
     */
    boolean hasStatus();
    /**
     * <code>optional .google.rpc.Status status = 2 [json_name = "status"];</code>
     * @return The status.
     */
    com.google.rpc.Status getStatus();
    /**
     * <code>optional .google.rpc.Status status = 2 [json_name = "status"];</code>
     */
    com.google.rpc.StatusOrBuilder getStatusOrBuilder();

    /**
     * <code>optional bytes payload = 3 [json_name = "payload"];</code>
     * @return Whether the payload field is set.
     */
    boolean hasPayload();
    /**
     * <code>optional bytes payload = 3 [json_name = "payload"];</code>
     * @return The payload.
     */
    com.google.protobuf.ByteString getPayload();
  }
  /**
   * Protobuf type {@code aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Response}
   */
  public static final class Response extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Response)
      ResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Response.newBuilder() to construct.
    private Response(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Response() {
      payload_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Response();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.aalyria.spacetime.api.cdpi.v1alpha.CdpiProto.internal_static_aalyria_spacetime_api_cdpi_v1alpha_CdpiRequest_Response_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.aalyria.spacetime.api.cdpi.v1alpha.CdpiProto.internal_static_aalyria_spacetime_api_cdpi_v1alpha_CdpiRequest_Response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Response.class, com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Response.Builder.class);
    }

    private int bitField0_;
    public static final int REQUEST_ID_FIELD_NUMBER = 1;
    private long requestId_ = 0L;
    /**
     * <code>optional int64 request_id = 1 [json_name = "requestId"];</code>
     * @return Whether the requestId field is set.
     */
    @java.lang.Override
    public boolean hasRequestId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional int64 request_id = 1 [json_name = "requestId"];</code>
     * @return The requestId.
     */
    @java.lang.Override
    public long getRequestId() {
      return requestId_;
    }

    public static final int STATUS_FIELD_NUMBER = 2;
    private com.google.rpc.Status status_;
    /**
     * <code>optional .google.rpc.Status status = 2 [json_name = "status"];</code>
     * @return Whether the status field is set.
     */
    @java.lang.Override
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional .google.rpc.Status status = 2 [json_name = "status"];</code>
     * @return The status.
     */
    @java.lang.Override
    public com.google.rpc.Status getStatus() {
      return status_ == null ? com.google.rpc.Status.getDefaultInstance() : status_;
    }
    /**
     * <code>optional .google.rpc.Status status = 2 [json_name = "status"];</code>
     */
    @java.lang.Override
    public com.google.rpc.StatusOrBuilder getStatusOrBuilder() {
      return status_ == null ? com.google.rpc.Status.getDefaultInstance() : status_;
    }

    public static final int PAYLOAD_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString payload_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>optional bytes payload = 3 [json_name = "payload"];</code>
     * @return Whether the payload field is set.
     */
    @java.lang.Override
    public boolean hasPayload() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional bytes payload = 3 [json_name = "payload"];</code>
     * @return The payload.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getPayload() {
      return payload_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt64(1, requestId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeMessage(2, getStatus());
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeBytes(3, payload_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, requestId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getStatus());
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, payload_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Response)) {
        return super.equals(obj);
      }
      com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Response other = (com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Response) obj;

      if (hasRequestId() != other.hasRequestId()) return false;
      if (hasRequestId()) {
        if (getRequestId()
            != other.getRequestId()) return false;
      }
      if (hasStatus() != other.hasStatus()) return false;
      if (hasStatus()) {
        if (!getStatus()
            .equals(other.getStatus())) return false;
      }
      if (hasPayload() != other.hasPayload()) return false;
      if (hasPayload()) {
        if (!getPayload()
            .equals(other.getPayload())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasRequestId()) {
        hash = (37 * hash) + REQUEST_ID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getRequestId());
      }
      if (hasStatus()) {
        hash = (37 * hash) + STATUS_FIELD_NUMBER;
        hash = (53 * hash) + getStatus().hashCode();
      }
      if (hasPayload()) {
        hash = (37 * hash) + PAYLOAD_FIELD_NUMBER;
        hash = (53 * hash) + getPayload().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Response parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Response parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Response prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Response}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Response)
        com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.ResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.aalyria.spacetime.api.cdpi.v1alpha.CdpiProto.internal_static_aalyria_spacetime_api_cdpi_v1alpha_CdpiRequest_Response_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.aalyria.spacetime.api.cdpi.v1alpha.CdpiProto.internal_static_aalyria_spacetime_api_cdpi_v1alpha_CdpiRequest_Response_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Response.class, com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Response.Builder.class);
      }

      // Construct using com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Response.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getStatusFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        requestId_ = 0L;
        status_ = null;
        if (statusBuilder_ != null) {
          statusBuilder_.dispose();
          statusBuilder_ = null;
        }
        payload_ = com.google.protobuf.ByteString.EMPTY;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.aalyria.spacetime.api.cdpi.v1alpha.CdpiProto.internal_static_aalyria_spacetime_api_cdpi_v1alpha_CdpiRequest_Response_descriptor;
      }

      @java.lang.Override
      public com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Response getDefaultInstanceForType() {
        return com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Response.getDefaultInstance();
      }

      @java.lang.Override
      public com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Response build() {
        com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Response buildPartial() {
        com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Response result = new com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Response(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Response result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.requestId_ = requestId_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.status_ = statusBuilder_ == null
              ? status_
              : statusBuilder_.build();
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.payload_ = payload_;
          to_bitField0_ |= 0x00000004;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Response) {
          return mergeFrom((com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Response other) {
        if (other == com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Response.getDefaultInstance()) return this;
        if (other.hasRequestId()) {
          setRequestId(other.getRequestId());
        }
        if (other.hasStatus()) {
          mergeStatus(other.getStatus());
        }
        if (other.hasPayload()) {
          setPayload(other.getPayload());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                requestId_ = input.readInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                input.readMessage(
                    getStatusFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                payload_ = input.readBytes();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long requestId_ ;
      /**
       * <code>optional int64 request_id = 1 [json_name = "requestId"];</code>
       * @return Whether the requestId field is set.
       */
      @java.lang.Override
      public boolean hasRequestId() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional int64 request_id = 1 [json_name = "requestId"];</code>
       * @return The requestId.
       */
      @java.lang.Override
      public long getRequestId() {
        return requestId_;
      }
      /**
       * <code>optional int64 request_id = 1 [json_name = "requestId"];</code>
       * @param value The requestId to set.
       * @return This builder for chaining.
       */
      public Builder setRequestId(long value) {

        requestId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 request_id = 1 [json_name = "requestId"];</code>
       * @return This builder for chaining.
       */
      public Builder clearRequestId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        requestId_ = 0L;
        onChanged();
        return this;
      }

      private com.google.rpc.Status status_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.rpc.Status, com.google.rpc.Status.Builder, com.google.rpc.StatusOrBuilder> statusBuilder_;
      /**
       * <code>optional .google.rpc.Status status = 2 [json_name = "status"];</code>
       * @return Whether the status field is set.
       */
      public boolean hasStatus() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional .google.rpc.Status status = 2 [json_name = "status"];</code>
       * @return The status.
       */
      public com.google.rpc.Status getStatus() {
        if (statusBuilder_ == null) {
          return status_ == null ? com.google.rpc.Status.getDefaultInstance() : status_;
        } else {
          return statusBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .google.rpc.Status status = 2 [json_name = "status"];</code>
       */
      public Builder setStatus(com.google.rpc.Status value) {
        if (statusBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          status_ = value;
        } else {
          statusBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>optional .google.rpc.Status status = 2 [json_name = "status"];</code>
       */
      public Builder setStatus(
          com.google.rpc.Status.Builder builderForValue) {
        if (statusBuilder_ == null) {
          status_ = builderForValue.build();
        } else {
          statusBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>optional .google.rpc.Status status = 2 [json_name = "status"];</code>
       */
      public Builder mergeStatus(com.google.rpc.Status value) {
        if (statusBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0) &&
            status_ != null &&
            status_ != com.google.rpc.Status.getDefaultInstance()) {
            getStatusBuilder().mergeFrom(value);
          } else {
            status_ = value;
          }
        } else {
          statusBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>optional .google.rpc.Status status = 2 [json_name = "status"];</code>
       */
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000002);
        status_ = null;
        if (statusBuilder_ != null) {
          statusBuilder_.dispose();
          statusBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>optional .google.rpc.Status status = 2 [json_name = "status"];</code>
       */
      public com.google.rpc.Status.Builder getStatusBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getStatusFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .google.rpc.Status status = 2 [json_name = "status"];</code>
       */
      public com.google.rpc.StatusOrBuilder getStatusOrBuilder() {
        if (statusBuilder_ != null) {
          return statusBuilder_.getMessageOrBuilder();
        } else {
          return status_ == null ?
              com.google.rpc.Status.getDefaultInstance() : status_;
        }
      }
      /**
       * <code>optional .google.rpc.Status status = 2 [json_name = "status"];</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.rpc.Status, com.google.rpc.Status.Builder, com.google.rpc.StatusOrBuilder> 
          getStatusFieldBuilder() {
        if (statusBuilder_ == null) {
          statusBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.rpc.Status, com.google.rpc.Status.Builder, com.google.rpc.StatusOrBuilder>(
                  getStatus(),
                  getParentForChildren(),
                  isClean());
          status_ = null;
        }
        return statusBuilder_;
      }

      private com.google.protobuf.ByteString payload_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes payload = 3 [json_name = "payload"];</code>
       * @return Whether the payload field is set.
       */
      @java.lang.Override
      public boolean hasPayload() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional bytes payload = 3 [json_name = "payload"];</code>
       * @return The payload.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getPayload() {
        return payload_;
      }
      /**
       * <code>optional bytes payload = 3 [json_name = "payload"];</code>
       * @param value The payload to set.
       * @return This builder for chaining.
       */
      public Builder setPayload(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        payload_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes payload = 3 [json_name = "payload"];</code>
       * @return This builder for chaining.
       */
      public Builder clearPayload() {
        bitField0_ = (bitField0_ & ~0x00000004);
        payload_ = getDefaultInstance().getPayload();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Response)
    }

    // @@protoc_insertion_point(class_scope:aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Response)
    private static final com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Response DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Response();
    }

    public static com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Response getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Response>
        PARSER = new com.google.protobuf.AbstractParser<Response>() {
      @java.lang.Override
      public Response parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Response> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Response> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Response getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private int bitField0_;
  public static final int HELLO_FIELD_NUMBER = 1;
  private com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Hello hello_;
  /**
   * <code>optional .aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Hello hello = 1 [json_name = "hello"];</code>
   * @return Whether the hello field is set.
   */
  @java.lang.Override
  public boolean hasHello() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional .aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Hello hello = 1 [json_name = "hello"];</code>
   * @return The hello.
   */
  @java.lang.Override
  public com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Hello getHello() {
    return hello_ == null ? com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Hello.getDefaultInstance() : hello_;
  }
  /**
   * <code>optional .aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Hello hello = 1 [json_name = "hello"];</code>
   */
  @java.lang.Override
  public com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.HelloOrBuilder getHelloOrBuilder() {
    return hello_ == null ? com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Hello.getDefaultInstance() : hello_;
  }

  public static final int RESPONSE_FIELD_NUMBER = 2;
  private com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Response response_;
  /**
   * <code>optional .aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Response response = 2 [json_name = "response"];</code>
   * @return Whether the response field is set.
   */
  @java.lang.Override
  public boolean hasResponse() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional .aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Response response = 2 [json_name = "response"];</code>
   * @return The response.
   */
  @java.lang.Override
  public com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Response getResponse() {
    return response_ == null ? com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Response.getDefaultInstance() : response_;
  }
  /**
   * <code>optional .aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Response response = 2 [json_name = "response"];</code>
   */
  @java.lang.Override
  public com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.ResponseOrBuilder getResponseOrBuilder() {
    return response_ == null ? com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Response.getDefaultInstance() : response_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getHello());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(2, getResponse());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getHello());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getResponse());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest)) {
      return super.equals(obj);
    }
    com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest other = (com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest) obj;

    if (hasHello() != other.hasHello()) return false;
    if (hasHello()) {
      if (!getHello()
          .equals(other.getHello())) return false;
    }
    if (hasResponse() != other.hasResponse()) return false;
    if (hasResponse()) {
      if (!getResponse()
          .equals(other.getResponse())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasHello()) {
      hash = (37 * hash) + HELLO_FIELD_NUMBER;
      hash = (53 * hash) + getHello().hashCode();
    }
    if (hasResponse()) {
      hash = (37 * hash) + RESPONSE_FIELD_NUMBER;
      hash = (53 * hash) + getResponse().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest)
      com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.aalyria.spacetime.api.cdpi.v1alpha.CdpiProto.internal_static_aalyria_spacetime_api_cdpi_v1alpha_CdpiRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.aalyria.spacetime.api.cdpi.v1alpha.CdpiProto.internal_static_aalyria_spacetime_api_cdpi_v1alpha_CdpiRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.class, com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Builder.class);
    }

    // Construct using com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getHelloFieldBuilder();
        getResponseFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      hello_ = null;
      if (helloBuilder_ != null) {
        helloBuilder_.dispose();
        helloBuilder_ = null;
      }
      response_ = null;
      if (responseBuilder_ != null) {
        responseBuilder_.dispose();
        responseBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.aalyria.spacetime.api.cdpi.v1alpha.CdpiProto.internal_static_aalyria_spacetime_api_cdpi_v1alpha_CdpiRequest_descriptor;
    }

    @java.lang.Override
    public com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest getDefaultInstanceForType() {
      return com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest build() {
      com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest buildPartial() {
      com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest result = new com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.hello_ = helloBuilder_ == null
            ? hello_
            : helloBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.response_ = responseBuilder_ == null
            ? response_
            : responseBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest) {
        return mergeFrom((com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest other) {
      if (other == com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.getDefaultInstance()) return this;
      if (other.hasHello()) {
        mergeHello(other.getHello());
      }
      if (other.hasResponse()) {
        mergeResponse(other.getResponse());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getHelloFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getResponseFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Hello hello_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Hello, com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Hello.Builder, com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.HelloOrBuilder> helloBuilder_;
    /**
     * <code>optional .aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Hello hello = 1 [json_name = "hello"];</code>
     * @return Whether the hello field is set.
     */
    public boolean hasHello() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional .aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Hello hello = 1 [json_name = "hello"];</code>
     * @return The hello.
     */
    public com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Hello getHello() {
      if (helloBuilder_ == null) {
        return hello_ == null ? com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Hello.getDefaultInstance() : hello_;
      } else {
        return helloBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Hello hello = 1 [json_name = "hello"];</code>
     */
    public Builder setHello(com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Hello value) {
      if (helloBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        hello_ = value;
      } else {
        helloBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>optional .aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Hello hello = 1 [json_name = "hello"];</code>
     */
    public Builder setHello(
        com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Hello.Builder builderForValue) {
      if (helloBuilder_ == null) {
        hello_ = builderForValue.build();
      } else {
        helloBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>optional .aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Hello hello = 1 [json_name = "hello"];</code>
     */
    public Builder mergeHello(com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Hello value) {
      if (helloBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          hello_ != null &&
          hello_ != com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Hello.getDefaultInstance()) {
          getHelloBuilder().mergeFrom(value);
        } else {
          hello_ = value;
        }
      } else {
        helloBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>optional .aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Hello hello = 1 [json_name = "hello"];</code>
     */
    public Builder clearHello() {
      bitField0_ = (bitField0_ & ~0x00000001);
      hello_ = null;
      if (helloBuilder_ != null) {
        helloBuilder_.dispose();
        helloBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>optional .aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Hello hello = 1 [json_name = "hello"];</code>
     */
    public com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Hello.Builder getHelloBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getHelloFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Hello hello = 1 [json_name = "hello"];</code>
     */
    public com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.HelloOrBuilder getHelloOrBuilder() {
      if (helloBuilder_ != null) {
        return helloBuilder_.getMessageOrBuilder();
      } else {
        return hello_ == null ?
            com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Hello.getDefaultInstance() : hello_;
      }
    }
    /**
     * <code>optional .aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Hello hello = 1 [json_name = "hello"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Hello, com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Hello.Builder, com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.HelloOrBuilder> 
        getHelloFieldBuilder() {
      if (helloBuilder_ == null) {
        helloBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Hello, com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Hello.Builder, com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.HelloOrBuilder>(
                getHello(),
                getParentForChildren(),
                isClean());
        hello_ = null;
      }
      return helloBuilder_;
    }

    private com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Response response_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Response, com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Response.Builder, com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.ResponseOrBuilder> responseBuilder_;
    /**
     * <code>optional .aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Response response = 2 [json_name = "response"];</code>
     * @return Whether the response field is set.
     */
    public boolean hasResponse() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional .aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Response response = 2 [json_name = "response"];</code>
     * @return The response.
     */
    public com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Response getResponse() {
      if (responseBuilder_ == null) {
        return response_ == null ? com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Response.getDefaultInstance() : response_;
      } else {
        return responseBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Response response = 2 [json_name = "response"];</code>
     */
    public Builder setResponse(com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Response value) {
      if (responseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        response_ = value;
      } else {
        responseBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>optional .aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Response response = 2 [json_name = "response"];</code>
     */
    public Builder setResponse(
        com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Response.Builder builderForValue) {
      if (responseBuilder_ == null) {
        response_ = builderForValue.build();
      } else {
        responseBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>optional .aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Response response = 2 [json_name = "response"];</code>
     */
    public Builder mergeResponse(com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Response value) {
      if (responseBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          response_ != null &&
          response_ != com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Response.getDefaultInstance()) {
          getResponseBuilder().mergeFrom(value);
        } else {
          response_ = value;
        }
      } else {
        responseBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>optional .aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Response response = 2 [json_name = "response"];</code>
     */
    public Builder clearResponse() {
      bitField0_ = (bitField0_ & ~0x00000002);
      response_ = null;
      if (responseBuilder_ != null) {
        responseBuilder_.dispose();
        responseBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>optional .aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Response response = 2 [json_name = "response"];</code>
     */
    public com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Response.Builder getResponseBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getResponseFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Response response = 2 [json_name = "response"];</code>
     */
    public com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.ResponseOrBuilder getResponseOrBuilder() {
      if (responseBuilder_ != null) {
        return responseBuilder_.getMessageOrBuilder();
      } else {
        return response_ == null ?
            com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Response.getDefaultInstance() : response_;
      }
    }
    /**
     * <code>optional .aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Response response = 2 [json_name = "response"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Response, com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Response.Builder, com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.ResponseOrBuilder> 
        getResponseFieldBuilder() {
      if (responseBuilder_ == null) {
        responseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Response, com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.Response.Builder, com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest.ResponseOrBuilder>(
                getResponse(),
                getParentForChildren(),
                isClean());
        response_ = null;
      }
      return responseBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest)
  }

  // @@protoc_insertion_point(class_scope:aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest)
  private static final com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest();
  }

  public static com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<CdpiRequest>
      PARSER = new com.google.protobuf.AbstractParser<CdpiRequest>() {
    @java.lang.Override
    public CdpiRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<CdpiRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CdpiRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.aalyria.spacetime.api.cdpi.v1alpha.CdpiRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

